AllCops:
  Exclude:
    - industry.gemspec

Style/ModuleFunction:
  Exclude:
    - "lib/industry/utils.rb"

Metrics/LineLength:
  Max: 100

Metrics/ModuleLength:
  Exclude:
    - "**/*_spec.rb"

Metrics/BlockLength:
  Exclude:
    - "**/*_spec.rb"

Metrics/MethodLength:
  Max: 15

Metrics/ParameterLists:
  Max: 7